import type { TemplateTokens } from "./types";

/**
 * 10 ATS-friendly templates. They are deliberately distinct in *silhouette* —
 * filled colored sidebars, tinted sidebars, editorial side-label gutters,
 * two-column newspaper bodies, full-width bands and top rules — not just color
 * and font, so they read as different designs even at thumbnail scale. All
 * variety is expressed as tokens so the renderers stay DRY.
 */
export const TEMPLATES: TemplateTokens[] = [
  {
    id: "classic",
    label: "Classic",
    description: "Timeless centered header over ruled, uppercase section titles.",
    layout: "single",
    headerAlign: "center",
    sectionTitle: "uppercase",
    divider: true,
    accent: "rule",
    density: "normal",
    font: "inter",
    accentColor: "#1d4ed8",
    nameSize: 32,
    headerStyle: "underline",
    contactStyle: "inline",
    bullet: "disc",
  },
  {
    id: "minimal",
    label: "Minimal",
    description: "Editorial side-label layout: tiny titles in a gutter, airy and monochrome.",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "capitalize",
    divider: false,
    accent: "none",
    density: "roomy",
    font: "inter",
    accentColor: "#111827",
    nameSize: 28,
    headerStyle: "plain",
    contactStyle: "inline",
    bullet: "dash",
    sectionLayout: "side-label",
    titleUnderline: false,
  },
  {
    id: "professional",
    label: "Professional",
    description: "Bold filled sidebar holds your name, contact and skills. Corporate-ready.",
    layout: "two-column",
    headerAlign: "left",
    sectionTitle: "uppercase",
    divider: false,
    accent: "sidebar",
    density: "normal",
    font: "lato",
    accentColor: "#0f766e",
    nameSize: 26,
    headerStyle: "plain",
    contactStyle: "stacked",
    bullet: "square",
    sidebarStyle: "filled",
    sidebarSide: "left",
    monogram: true,
  },
  {
    id: "compact",
    label: "Compact",
    description: "Two-column newspaper flow packs dense, senior resumes onto one page.",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "uppercase",
    divider: true,
    accent: "rule",
    density: "compact",
    font: "source",
    accentColor: "#4338ca",
    nameSize: 24,
    headerStyle: "underline",
    contactStyle: "inline",
    bullet: "square",
    bodyColumns: 2,
  },
  {
    id: "modern-serif",
    label: "Modern Serif",
    description: "Editorial serif with a thin top rule and an oversized colored name.",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "smallcaps",
    divider: true,
    accent: "name",
    density: "normal",
    font: "merriweather",
    accentColor: "#9333ea",
    nameSize: 38,
    headerStyle: "plain",
    contactStyle: "inline",
    bullet: "disc",
    topRule: true,
    titleUnderline: true,
  },
  {
    id: "technical",
    label: "Technical",
    description: "Engineer card: boxed header, left accent bars on every section, tight spacing.",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "bar",
    divider: false,
    accent: "rule",
    density: "compact",
    font: "source",
    accentColor: "#2563eb",
    nameSize: 27,
    headerStyle: "boxed",
    contactStyle: "stacked",
    bullet: "dash",
  },
  {
    id: "executive",
    label: "Executive",
    description: "Centered name in a full-width dark accent band. Formal and commanding.",
    layout: "single",
    headerAlign: "center",
    sectionTitle: "uppercase",
    divider: true,
    accent: "rule",
    density: "normal",
    font: "lato",
    accentColor: "#0f172a",
    nameSize: 34,
    headerStyle: "band",
    contactStyle: "inline",
    bullet: "disc",
    uppercaseName: true,
    letterSpacedName: true,
  },
  {
    id: "academic",
    label: "Academic",
    description: "Roomy serif CV with stacked contacts and underlined headings — ideal for research.",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "capitalize",
    divider: false,
    accent: "none",
    density: "roomy",
    font: "merriweather",
    accentColor: "#1f2937",
    nameSize: 30,
    headerStyle: "underline",
    contactStyle: "stacked",
    bullet: "disc",
    titleUnderline: true,
  },
  {
    id: "two-column-ats",
    label: "Two Column",
    description: "Tinted right sidebar for skills & languages — still cleanly ATS-parseable.",
    layout: "two-column",
    headerAlign: "left",
    sectionTitle: "uppercase",
    divider: true,
    accent: "heading",
    density: "normal",
    font: "inter",
    accentColor: "#0369a1",
    nameSize: 30,
    headerStyle: "underline",
    contactStyle: "inline",
    bullet: "disc",
    sidebarTint: true,
    sidebarSide: "right",
  },
  {
    id: "elegant",
    label: "Elegant",
    description: "Centered small-caps headings, hairline rules and wide tracking. Refined.",
    layout: "single",
    headerAlign: "center",
    sectionTitle: "smallcaps",
    divider: true,
    accent: "heading",
    density: "roomy",
    font: "lato",
    accentColor: "#9f1239",
    nameSize: 34,
    headerStyle: "plain",
    contactStyle: "inline",
    bullet: "none",
    letterSpacedName: true,
    titleUnderline: false,
  },
  {
    id: "aurora-sidebar",
    label: "Aurora Sidebar",
    description: "Premium split layout with a vivid green sidebar and bold monogram block.",
    access: "pro",
    layout: "two-column",
    headerAlign: "left",
    sectionTitle: "bar",
    divider: false,
    accent: "sidebar",
    density: "normal",
    font: "inter",
    accentColor: "#059669",
    nameSize: 30,
    headerStyle: "plain",
    contactStyle: "stacked",
    bullet: "dash",
    sidebarStyle: "filled",
    sidebarSide: "left",
    monogram: true,
    accentChip: true,
  },
  {
    id: "noir-executive",
    label: "Noir Executive",
    description: "Premium black-band executive CV with uppercase presence and sharp rules.",
    access: "pro",
    layout: "single",
    headerAlign: "center",
    sectionTitle: "smallcaps",
    divider: true,
    accent: "rule",
    density: "roomy",
    font: "lato",
    accentColor: "#020617",
    nameSize: 38,
    headerStyle: "band",
    contactStyle: "inline",
    bullet: "none",
    uppercaseName: true,
    letterSpacedName: true,
    titleUnderline: true,
  },
  {
    id: "cobalt-grid",
    label: "Cobalt Grid",
    description: "Premium dense two-column grid for product, data and technical profiles.",
    access: "pro",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "bar",
    divider: true,
    accent: "heading",
    density: "compact",
    font: "source",
    accentColor: "#1d4ed8",
    nameSize: 28,
    headerStyle: "boxed",
    contactStyle: "stacked",
    bullet: "square",
    bodyColumns: 2,
    accentChip: true,
    topRule: true,
  },
  {
    id: "rose-editorial",
    label: "Rose Editorial",
    description: "Premium magazine-style serif resume with a rose accent and airy side labels.",
    access: "pro",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "smallcaps",
    divider: false,
    accent: "name",
    density: "roomy",
    font: "merriweather",
    accentColor: "#be123c",
    nameSize: 40,
    headerStyle: "plain",
    contactStyle: "inline",
    bullet: "disc",
    sectionLayout: "side-label",
    topRule: true,
    titleUnderline: false,
  },
  {
    id: "obsidian-band",
    label: "Obsidian Band",
    description: "Premium dramatic header band with compact sections and strong contrast.",
    access: "pro",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "uppercase",
    divider: true,
    accent: "rule",
    density: "compact",
    font: "inter",
    accentColor: "#18181b",
    nameSize: 34,
    headerStyle: "band",
    contactStyle: "inline",
    bullet: "dash",
    uppercaseName: true,
  },
  {
    id: "emerald-mono",
    label: "Emerald Mono",
    description: "Premium technical layout with an emerald system feel and tight hierarchy.",
    access: "pro",
    layout: "two-column",
    headerAlign: "left",
    sectionTitle: "bar",
    divider: false,
    accent: "sidebar",
    density: "compact",
    font: "source",
    accentColor: "#047857",
    nameSize: 27,
    headerStyle: "boxed",
    contactStyle: "stacked",
    bullet: "square",
    sidebarTint: true,
    sidebarSide: "right",
    accentChip: true,
  },
  {
    id: "atelier-serif",
    label: "Atelier Serif",
    description: "Premium creative serif layout with oversized name and refined section rhythm.",
    access: "pro",
    layout: "single",
    headerAlign: "center",
    sectionTitle: "capitalize",
    divider: true,
    accent: "name",
    density: "roomy",
    font: "merriweather",
    accentColor: "#7c2d12",
    nameSize: 42,
    headerStyle: "underline",
    contactStyle: "inline",
    bullet: "disc",
    letterSpacedName: true,
    titleUnderline: true,
  },
  {
    id: "kinetic-column",
    label: "Kinetic Column",
    description: "Premium asymmetric column design with a right-side accent panel.",
    access: "pro",
    layout: "two-column",
    headerAlign: "left",
    sectionTitle: "uppercase",
    divider: true,
    accent: "heading",
    density: "normal",
    font: "lato",
    accentColor: "#7e22ce",
    nameSize: 32,
    headerStyle: "underline",
    contactStyle: "inline",
    bullet: "dash",
    sidebarTint: true,
    sidebarSide: "right",
    monogram: true,
  },
  {
    id: "solar-impact",
    label: "Solar Impact",
    description: "Premium high-energy CV with warm accent chips and compact impact sections.",
    access: "pro",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "bar",
    divider: false,
    accent: "heading",
    density: "normal",
    font: "lato",
    accentColor: "#ca8a04",
    nameSize: 35,
    headerStyle: "boxed",
    contactStyle: "stacked",
    bullet: "square",
    accentChip: true,
    topRule: true,
  },
  {
    id: "crimson-portfolio",
    label: "Crimson Portfolio",
    description: "Premium portfolio-forward resume with crimson heading chips and bold spacing.",
    access: "pro",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "uppercase",
    divider: true,
    accent: "heading",
    density: "roomy",
    font: "inter",
    accentColor: "#991b1b",
    nameSize: 36,
    headerStyle: "plain",
    contactStyle: "inline",
    bullet: "dash",
    accentChip: true,
    letterSpacedName: true,
  },
  {
    id: "midnight-academic",
    label: "Midnight Academic",
    description: "Premium academic CV with a midnight sidebar and publication-friendly density.",
    access: "pro",
    layout: "two-column",
    headerAlign: "left",
    sectionTitle: "capitalize",
    divider: false,
    accent: "sidebar",
    density: "roomy",
    font: "merriweather",
    accentColor: "#1e293b",
    nameSize: 30,
    headerStyle: "plain",
    contactStyle: "stacked",
    bullet: "disc",
    sidebarStyle: "filled",
    sidebarSide: "left",
    titleUnderline: true,
  },
  {
    id: "electric-technical",
    label: "Electric Technical",
    description: "Premium engineering template with bright blue section bars and boxed header.",
    access: "pro",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "bar",
    divider: false,
    accent: "rule",
    density: "compact",
    font: "source",
    accentColor: "#0284c7",
    nameSize: 29,
    headerStyle: "boxed",
    contactStyle: "stacked",
    bullet: "dash",
    bodyColumns: 2,
    topRule: true,
  },
];

export const FREE_DRAFT_LIMIT = 5;
export const FREE_TEMPLATES = TEMPLATES.filter((t) => t.access !== "pro");
export const PRO_TEMPLATES = TEMPLATES.filter((t) => t.access === "pro");

export const TEMPLATE_LABELS: Record<string, string> = Object.fromEntries(
  TEMPLATES.map((t) => [t.id, t.label]),
);

export function getTemplate(id: string): TemplateTokens {
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0]!;
}

export function getTemplateAccess(id: string) {
  return getTemplate(id).access ?? "free";
}

export function isProTemplate(id: string) {
  return getTemplateAccess(id) === "pro";
}
