import type { TemplateTokens } from "./types";

/**
 * 10 ATS-friendly templates. They differ in layout, accent usage, section-title
 * styling, density and default font — all expressed as tokens.
 */
export const TEMPLATES: TemplateTokens[] = [
  {
    id: "classic",
    label: "Classic",
    description: "Timeless single-column layout with ruled section headers.",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "uppercase",
    divider: true,
    accent: "rule",
    density: "normal",
    font: "inter",
    accentColor: "#2563eb",
    nameSize: 30,
  },
  {
    id: "minimal",
    label: "Minimal",
    description: "Clean, understated, lots of whitespace. No color.",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "capitalize",
    divider: false,
    accent: "none",
    density: "roomy",
    font: "inter",
    accentColor: "#111827",
    nameSize: 28,
  },
  {
    id: "professional",
    label: "Professional",
    description: "Confident headers with colored section titles.",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "uppercase",
    divider: true,
    accent: "heading",
    density: "normal",
    font: "lato",
    accentColor: "#0f766e",
    nameSize: 30,
  },
  {
    id: "compact",
    label: "Compact",
    description: "Fits more on a page — ideal for senior, detailed resumes.",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "uppercase",
    divider: true,
    accent: "rule",
    density: "compact",
    font: "source",
    accentColor: "#4338ca",
    nameSize: 26,
  },
  {
    id: "modern-serif",
    label: "Modern Serif",
    description: "Editorial serif headings with a colored name.",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "smallcaps",
    divider: true,
    accent: "name",
    density: "normal",
    font: "merriweather",
    accentColor: "#9333ea",
    nameSize: 32,
  },
  {
    id: "technical",
    label: "Technical",
    description: "Engineer-friendly with a left accent bar on sections.",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "bar",
    divider: false,
    accent: "rule",
    density: "compact",
    font: "source",
    accentColor: "#2563eb",
    nameSize: 28,
  },
  {
    id: "executive",
    label: "Executive",
    description: "Centered header, large name, formal tone.",
    layout: "single",
    headerAlign: "center",
    sectionTitle: "uppercase",
    divider: true,
    accent: "rule",
    density: "normal",
    font: "lato",
    accentColor: "#1f2937",
    nameSize: 34,
  },
  {
    id: "academic",
    label: "Academic",
    description: "Roomy serif layout suited to CVs and research.",
    layout: "single",
    headerAlign: "left",
    sectionTitle: "capitalize",
    divider: true,
    accent: "none",
    density: "roomy",
    font: "merriweather",
    accentColor: "#111827",
    nameSize: 30,
  },
  {
    id: "two-column-ats",
    label: "Two Column",
    description: "Sidebar for skills & contact, kept ATS-parseable.",
    layout: "two-column",
    headerAlign: "left",
    sectionTitle: "uppercase",
    divider: false,
    accent: "sidebar",
    density: "normal",
    font: "inter",
    accentColor: "#0ea5e9",
    nameSize: 28,
  },
  {
    id: "elegant",
    label: "Elegant",
    description: "Centered, small-caps headings, generous spacing.",
    layout: "single",
    headerAlign: "center",
    sectionTitle: "smallcaps",
    divider: false,
    accent: "heading",
    density: "roomy",
    font: "lato",
    accentColor: "#b91c1c",
    nameSize: 32,
  },
];

export const TEMPLATE_LABELS: Record<string, string> = Object.fromEntries(
  TEMPLATES.map((t) => [t.id, t.label]),
);

export function getTemplate(id: string): TemplateTokens {
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0]!;
}
